# Default values for spark-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# By default the chart deploys 1 master, the replica count stated here controls the number of workers.
replicaCount: 4

# Here you can specify the DSRS image to be used
image:
  repository: image-registry.openshift-image-registry.svc:5000/spark/dsrs-spark-centos:<image-tag>
  pullPolicy: IfNotPresent

# Here you can specify the resources for each pod
resources:
  requests:
    memory: "2Gi"
    cpu: "2"
  limits:
    memory: "8Gi"
    cpu: "4"
