{{- if .Values.enableClientToolsPod }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client-tools-pod
  labels:
    {{- $appLabel := printf "%s-%s" .Release.Name .Values.appLabelSuffix }}
    app: {{ $appLabel }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $appLabel }}
  template:
    metadata:
      labels:
        app: {{ $appLabel }}
    spec:
      containers:
      - name: {{ .Release.Name }}-client-tools-pod
        image: {{ .Values.clientToolsImage.name  }}
        imagePullPolicy: {{ .Values.clientToolsImage.pullPolicy }}
        volumeMounts:
          - name: test-profiles-volume
            mountPath: /testProfiles
          - name: client-tools-volume
            mountPath: /mnt/pmem0
      volumes:
        - name: test-profiles-volume
          configMap:
            name: {{ .Release.Name }}-test-profiles-configmap
        - name: client-tools-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-cassandra-pmem-client-tools-pvc
{{- end }}
