# DLaaS / Clear Linux related variables
include ../../config.make

# DLaaS MKL / Clear Linux related variables
OS=clearlinux
VERSION=mkl
DL_LIB=tensorflow
SERVER_LIB=openvino-omp
DOWNSTREAM=dlrs

# docker related variables
BUILDER_DOCKER_NAME_MKL?=stacks-$(VERSION)-builder
TF_DOCKER_NAME_MKL?=stacks-tf-$(VERSION)
SERVER_DOCKER_NAME_MKL?=stacks-$(SERVER_LIB)
CLR_DOWNSTREAM_DOCKER_NAME_MKL?=$(OS)-$(DOWNSTREAM)-builder
DOWNSTREAM_DOCKER_NAME_MKL?=stacks-$(DL_LIB)-$(VERSION)
DOCKER_NAME_MKL_AIXPRT?=stacks-tensorflow-$(VERSION)-omp-aixprt

# append the postfix random name if present so we create random names for
# docker images and containers
ifdef DOCKER_RANDOM_POSTFIX
BUILDER_DOCKER_NAME_MKL?=stacks-$(VERSION)-builder-$(DOCKER_RANDOM_POSTFIX)
TF_DOCKER_NAME_MKL:=$(TF_DOCKER_NAME_MKL)-$(DOCKER_RANDOM_POSTFIX)
SERVER_DOCKER_NAME_MKL:=$(SERVER_DOCKER_NAME_MKL)-$(DOCKER_RANDOM_POSTFIX)
CLR_DOWNSTREAM_DOCKER_NAME_MKL:=$(CLR_DOWNSTREAM_DOCKER_NAME_MKL)-$(DOCKER_RANDOM_POSTFIX)
DOWNSTREAM_DOCKER_NAME_MKL:=$(DOWNSTREAM_DOCKER_NAME_MKL)-$(DOCKER_RANDOM_POSTFIX)
endif

BUILDER_DOCKER_IMAGE_MKL?=$(BUILDER_DOCKER_NAME_MKL)
TF_DOCKER_IMAGE_MKL?=$(TF_DOCKER_NAME_MKL)
SERVER_DOCKER_IMAGE_MKL?=$(SERVER_DOCKER_NAME_MKL)
CLR_DOWNSTREAM_DOCKER_IMAGE_MKL?=$(CLR_DOWNSTREAM_DOCKER_NAME_MKL)
DOWNSTREAM_DOCKER_IMAGE_MKL?=$(DOWNSTREAM_DOCKER_NAME_MKL)
DOCKER_IMAGE_MKL_AIXPRT?=$(DOCKER_NAME_MKL_AIXPRT)

DOCKER_SHELL?=bash
BUILDER_DOCKER_FILE?=../$(VERSION)/Dockerfile.builder
TF_DOCKER_FILE?=../$(VERSION)/Dockerfile.tf
SERVER_DOCKER_FILE?=../$(VERSION)/Dockerfile.openvino
CLR_DOWNSTREAM_DOCKER_FILE?=../$(VERSION)/Dockerfile.clr_ds
DOWNSTREAM_DOCKER_FILE?=../$(VERSION)/Dockerfile.dlrs
DOCKER_FILE_AIXPRT?=../$(VERSION)/Dockerfile.aixprt

VERSION_DIR=$(shell pwd)
