#---------------------------------------------------------------------
# Base instance to build MKL based Tensorflow on Clear Linux
#---------------------------------------------------------------------
FROM stacks-mkl-builder as base
LABEL maintainer=otc-swstacks@intel.com

RUN cd /usr/lib64/ && ln -sf libzstd.so.1.4.* libzstd.so.1
RUN swupd clean \
    && swupd bundle-add devpkg-opencv devpkg-llvm 

RUN ./scripts/build_openvino_ie.sh
