apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: 7077
    targetPort: 7077
    name: spark-url
  - port: 8080
    targetPort: 8080
    name: spark-web-ui
  clusterIP: None
  selector:
    app: {{ .Release.Name }}

